# docker-compose.yml (with custom networking)
version: '3.9'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - app_network
    ports:
      - "5432:5432"
networks:
  app_network:
    driver: bridge

